name: node

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    timeout-minutes: 1800

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Enable IP forwarding
        run: |
          sudo sysctl -w net.ipv4.ip_forward=1
          sudo sysctl -w net.ipv6.conf.all.forwarding=1

      - name: Advertise exit node
        run: |
          sudo tailscale set \
            --hostname=github-runner \
            --advertise-exit-node

      - name: Keep alive
        run: |
          for i in {1..300}; do
            echo "Still alive ($i/300)"
            sleep 60
          done
